---
- hosts: datamanager
  become: yes
  vars_files:
    - configs/credentials.yml
  roles:
    - xrootd
    - datamanager

# - hosts: dataserver
#   become: yes
#   vars_files:
#     - configs/credentials.yml
#   roles:
#     - xrootd
#     - dataserver

- hosts: cachingproxy
  become: yes
  vars_files:
    - configs/credentials.yml
  roles:
    - xrootd
    - cachingproxy

- hosts: extDataserver
  become: yes
  vars_files:
    - configs/credentials.yml
  roles:
    - xrootd
    - extDataserver

- hosts: client
  become: yes
  vars_files:
    - configs/credentials.yml
  roles:
    - xrootd
    - client
