#YUM mirror/http proxy settings
http_proxy: none #SET TO none if no proxy needed. The Proxy through which the YUM mirrors have to be accessed
http_port: 8080

#centos settings
testuser: vagrant

#XRootD Dataserver config
xrootd_port: 1094
xrootd_localroot: /tmp/shfs
enable_testfiles: false
xrootd_http_port: 1095

#Firewalld
enable_firewalld: false

#xrootd server config
datamanager_ip: 192.168.60.200
datamanager_port: 1094
datamanager_cmsd_port: 1095
dataserver_port: 1097
dataserver_cmsd_port: 1096
extDataserver_ip: 143.100.1.200
extDataserver_port: 1094
extDataserver_cmsd_port: 1095
cachingproxy_ip: 192.168.60.202
cachingproxy_port: 1094
